FRAME_PADDING = 3
ITEM_PADDING = 5

GREEN_HOVER = "#326A32"
GREEN_FG = "#469546"
BUTTON_BLUE_FG = "#428dff"
BUTTON_BLUE_HOVER = "#336DC5"
GRAY = ("gray10", "#DCE4EE")
DARK_GRAY = ("#979DA2", "#565B5E")

CHANGE_APPEARANCE_LABEL = "Change Appearance"
CHANGE_HOTKEY_LABEL = "Change Hotkey"
CLICK_EVENTS_LABEL = "Click Events"
CLICK_INTERVAL_LABEL = "Click Interval"
CLICK_LENGTH_LABEL = "Click Length"
CLICKS_PER_EVENT_LABEL = "Clicks Per Event"
CONFIRM_HOTKEY_LABEL = "Click to Confirm"
HOTKEY_ENTRY_RECORDING = "Press Key(s)"
HOTKEY_LABEL = "Hotkey"
HOURS_CHOICE = "Hours"
LOCATION_CONFIRM_LABEL = "Click Screen Location"
LOCATION_LABEL = "Location"
MILLISECONDS_CHOICE = "Milliseconds"
MINUTES_CHOICE = "Minutes"
MOUSE_1_CHOICE = "Left (M1)"
MOUSE_2_CHOICE = "Right (M2)"
MOUSE_3_CHOICE = "Middle (M3)"
MOUSE_BUTTON_LABEL = "Mouse Button"
PICK_LOCATION_LABEL = "Pick Location"
SECONDS_CHOICE = "Seconds"
START_BUTTON_LABEL = "Start"
STOP_BUTTON_LABEL = "Stop"

DEFAULT_CLICK_EVENTS = 0
DEFAULT_CLICKS_PER_EVENT = 1
DEFAULT_HOTKEY = "ctrl+f8"
DEFAULT_INTERVAL = 100
DEFAULT_LENGTH = 0

HOTKEY_MAX_KEYS = 3
MAX_CLICK_EVENTS_DIGITS = 6
MAX_CLICKS_PER_EVENT_DIGITS = 3
MAX_CLICK_INTERVAL_DIGITS = 6
MIN_CLICK_INTERVAL = 0

LOCATION_UPDATE_HARD_INTERVAL = 0.05
