name: Build for Linux

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    outputs:
      os_version:
        description: "Linux OS Version"
        value: ${{ jobs.build.outputs.os_version }}
      os_name:
        description: "Linux OS Name"
        value: ${{ jobs.build.outputs.os_name }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      os_version: ${{ steps.linux-version.outputs.os_version }}
      os_name: ${{ steps.linux-version.outputs.os_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Get Linux Version
        id: linux-version
        run: |
          OS_NAME=$(lsb_release -si)
          OS_VERSION=$(lsb_release -sr)
          echo "os_version=${OS_VERSION}" >> $GITHUB_OUTPUT
          echo "os_name=${OS_NAME}" >> $GITHUB_OUTPUT

      - name: Create Requirements.txt
        run: |
          cat > requirements.txt << 'EOL'
          customtkinter
          keyboard
          mouse
          pyautogui
          EOL

      - name: Download Python Dependencies
        run: |
          mkdir -p /tmp/python-packages
          pip download --dest /tmp/python-packages -r requirements.txt
          echo "Packages downloaded:"
          ls -la /tmp/python-packages

      - name: Install Flatpak and Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
          sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y flathub org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08

      - name: Create Flatpak Manifest
        run: |
          # Create a list of package files for installation
          PACKAGE_FILES=$(ls /tmp/python-packages/* | tr '\n' ' ')
          
          cat > com.easyautoclicker.EasyAutoClicker.yml << EOL
          app-id: com.easyautoclicker.EasyAutoClicker
          runtime: org.freedesktop.Platform
          runtime-version: '23.08'
          sdk: org.freedesktop.Sdk
          command: easyautoclicker
          finish-args:
            - --share=ipc
            - --socket=x11
            - --socket=wayland
            - --device=all
            - --filesystem=home
            - --talk-name=org.freedesktop.Notifications
          modules:
            - name: python3-dependencies
              buildsystem: simple
              build-commands:
                - python3 -m pip install --no-deps --prefix=/app ${PACKAGE_FILES}
              sources:
                - type: dir
                  path: /tmp/python-packages
              
            - name: easyautoclicker
              buildsystem: simple
              sources:
                - type: dir
                  path: .
              build-commands:
                - mkdir -p /app/bin
                - mkdir -p /app/share/applications
                - mkdir -p /app/share/icons/hicolor/256x256/apps
                - cp -r assets /app/share/easyautoclicker/
                - install -Dm755 app.py /app/bin/easyautoclicker
                - install -Dm644 assets/icon.ico /app/share/icons/hicolor/256x256/apps/com.easyautoclicker.EasyAutoClicker.ico
                - install -Dm644 com.easyautoclicker.EasyAutoClicker.desktop /app/share/applications/
          EOL

      - name: Create Desktop Entry
        run: |
          cat > com.easyautoclicker.EasyAutoClicker.desktop << 'EOL'
          [Desktop Entry]
          Name=EasyAutoClicker
          Comment=Starting automatic clicking processes via a simple GUI
          Exec=easyautoclicker
          Icon=com.easyautoclicker.EasyAutoClicker
          Terminal=false
          Type=Application
          Categories=Utility;
          Keywords=automation;click;auto;
          EOL

      - name: Build Flatpak Package
        run: |
          flatpak-builder --force-clean --repo=repo build-dir com.easyautoclicker.EasyAutoClicker.yml
          flatpak build-bundle repo EasyAutoClicker.flatpak com.easyautoclicker.EasyAutoClicker

      - name: Upload Flatpak Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-flatpak
          path: EasyAutoClicker.flatpak