name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter Version:'
        required: true
        type: string
      prerelease:
        description: 'Pre-release'
        required: true
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  build-windows:
    uses: ./.github/workflows/build-windows.yml
    with:
      version: ${{ inputs.version }}

  build-linux:
    uses: ./.github/workflows/build-linux.yml
    with:
      version: ${{ inputs.version }}

  create-release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Windows Installer
        uses: actions/download-artifact@v4
        with:
          name: windows-installer
          path: installer

      - name: Download Windows Build Archive
        uses: actions/download-artifact@v4
        with:
          name: windows-archive
          path: archives

      - name: Download Linux Build Archive
        uses: actions/download-artifact@v4
        with:
          name: linux-archive
          path: archives

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ inputs.version }}
          tag_name: v${{ inputs.version }}
          body: |
            ${{ inputs.description }}
            
            ### Build Environments
            **EasyAutoClicker-Setup-x64.exe:** Windows ${{ needs.build-windows.outputs.os_name }} (${{ needs.build-windows.outputs.os_version }})
            **EasyAutoClicker-${{ inputs.version }}-Win-x64.zip:** Windows ${{ needs.build-windows.outputs.os_name }} (${{ needs.build-windows.outputs.os_version }})
            **EasyAutoClicker-${{ inputs.version }}-Linux-x64.tar.gz:** ${{ needs.build-linux.outputs.ubuntu_version }}
            
            ### Changes

            - Changed lorem ipsum
          generate_release_notes: true
          prerelease: ${{ inputs.prerelease }}
          draft: true
          files: |
            installer/EasyAutoClicker-Setup-x64.exe
            archives/EasyAutoClicker-${{ inputs.version }}-Win-x64.zip
            archives/EasyAutoClicker-${{ inputs.version }}-Linux-x64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}