name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release Version"
        required: true
        type: string
        default: "0.0.0"
      pre-release:
        description: "Pre-release"
        required: true
        type: boolean
        default: false

permissions:
  contents: write

jobs:

  pyinstaller-build:
    uses: ./.github/workflows/pyinstaller-build.yml
    with:
      release-version: ${{ inputs.release_version }}

  create-release:
    needs: pyinstaller-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Ubuntu gZip
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-build

      - name: Download Windows Zip
        uses: actions/download-artifact@v4
        with:
          name: windows-build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ inputs.release_version }}
          tag_name: v${{ inputs.release_version }}
          body: |
            ### Build Environments
            **${{ needs.pyinstaller-build.outputs.windows_build_name }}:** ${{ needs.pyinstaller-build.outputs.windows_version }}
            **${{ needs.pyinstaller-build.outputs.ubuntu_build_name }}:** ${{ needs.pyinstaller-build.outputs.ubuntu_version }}
            
            ### Changes
            
            - Changed lorem ipsum
          generate_release_notes: true
          prerelease: ${{ inputs.pre-release }}
          draft: true
          files: |
            ${{ needs.pyinstaller-build.outputs.windows_build_name }}
            ${{ needs.pyinstaller-build.outputs.ubuntu_build_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}