name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type'
        required: true
        type: choice
        options:
          - Patch (0.0.x)
          - Minor (0.x.0)
          - Major (x.0.0)
      beta:
        description: 'Beta Version'
        required: true
        type: boolean
        default: false

permissions:
  contents: write

jobs:

  release-version:
    uses: ./.github/workflows/release-version.yml
    with:
      release_type: ${{ inputs.release_type }}
      beta: ${{ inputs.beta }}

  pyinstaller-build:
    needs: release-version
    uses: ./.github/workflows/pyinstaller-build.yml
    with:
      release-version: ${{ needs.release-version.outputs.release_version }}

  create-release:
    needs: [ pyinstaller-build, release-version ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Ubuntu gZip
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-build

      - name: Download Windows Zip
        uses: actions/download-artifact@v4
        with:
          name: windows-build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ needs.release-version.outputs.release_version }}
          tag_name: v${{ needs.release-version.outputs.release_version }}
          body: |
            ### Build Environments
            **${{ needs.pyinstaller-build.outputs.windows_build_name }}:** ${{ needs.pyinstaller-build.outputs.windows_version }}
            **${{ needs.pyinstaller-build.outputs.ubuntu_build_name }}:** ${{ needs.pyinstaller-build.outputs.ubuntu_version }}
            
            ### Changes
            
            - Changed lorem ipsum
          generate_release_notes: true
          prerelease: ${{ inputs.beta }}
          draft: true
          files: |
            ${{ needs.pyinstaller-build.outputs.windows_build_name }}
            ${{ needs.pyinstaller-build.outputs.ubuntu_build_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}