name: PyInstaller Build

on:
  workflow_dispatch:
    inputs:
      beta:
        description: 'Beta Version'
        required: true
        type: boolean
        default: false

jobs:
  pyinstaller-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

  pyinstaller-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt