name: Release Version

on:
  workflow_call:
    inputs:
      release_type:
        required: true
        type: string
      beta:
        required: true
        type: boolean
      version_override:
        required: true
        type: string
    outputs:
      release_version:
        value: ${{ jobs.determine-version.outputs.release_version }}

jobs:
  determine-version:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.version.outputs.release_version }}

    steps:
      - uses: actions/checkout@v4

      - name: Determine Release Version
        id: version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo chmod +x .github/workflows/scripts/ubuntu/release_version.sh
          .github/workflows/scripts/ubuntu/release_version.sh "${{ inputs.release_type }}" "${{ inputs.version_override }}" "${{ inputs.beta }}"